name: Grupo4

on:
  push:
    branches:
      - main
env:
  NOMBRE_GRUPO: "Grupo Nro4"
  CURSO: "Herramientas de Desarrollo"
  MOSTRAR_DESPEDIDA: "true"

jobs:
  workflow-grupo:
    runs-on: ubuntu-latest

    steps:
      
      - name: Prueba de mensajes
        run: |
          echo "Hola, bienvenidos integrantes del $NOMBRE_GRUPO"
          
      - name: Variables creada en el workflow
        run: |
          echo "Variable 1 - NOMBRE_GRUPO: $NOMBRE_GRUPO"
          echo "Variable 2 - CURSO: $CURSO"
          echo "Variable 3 - MOSTRAR_DESPEDIDA: $MOSTRAR_DESPEDIDA"

      - name: Variables del entorno del Github Actions
        run: |
          echo "Nombre del repositorio: $GITHUB_REPOSITORY"
          echo "Dueño del repositorio: $GITHUB_REPOSITORY_OWNER"
          echo "Nombre del workflow: $GITHUB_WORKFLOW"

      - name: Con Despedida
        if: env.MOSTRAR_DESPEDIDA == 'true'
        run: |
          echo "Hasta luego, integrantes del $NOMBRE_GRUPO"

      - name: Sin despedida
        if: env.MOSTRAR_DESPEDIDA == 'false'
        run: |
          echo "Este mensaje no se mostrará porque la condición es falsa"
          
      - name: Archivo JSON
        run: |
          echo "El contexto de JSON DEL evento es"
          echo '${{ toJson(github)}}'
          














    
